### ISSUE TITLE
[iOS] Combine II - Combine 기초: Sueaty 블로그

### ISSUE THREAD

**Issue by yeonduing** [Sueaty/iOS-Interview-KR#10]
> Sueaty 블로그의 [Combine II - Combine 기초](https://sueaty.tistory.com/141?category=867436) 중 Generic에 관한 질문입니다.

<img width="762" alt="스크린샷 2021-02-11 오후 4 09 24" src="https://user-images.githubusercontent.com/60538517/107610237-805d1980-6c84-11eb-9ccd-e9a989ed6b60.png">

위 글에서 2개의 값을 Generic으로 쓰고 있다고 했는데 `Result`가 아니라 `Generic`이 맞는지 궁금합니다.

Publisher.Output 타입을 채택하면 되는 형태로 `Generic`인건지 잘 모르겠어서 질문남깁니다.

**Comment by Sueaty** [comment]
해석에 제가 포인트를 잘못 준 것 같습니다. 원문은
```The Publisher protocol is generic over two types``` 로 나와있습니다.
```Publisher는 2개의 타입(Output, Failure)에 대해 generic(지정된 타입을 사용하게 됨)하게 사용할 수 있다.``` 로 작성하면
조금 이해하기 수월해질까요?
